//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Colorshop2Entities : DbContext
    {
        public Colorshop2Entities()
            : base("name=Colorshop2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Product> Products { get; set; }

        public System.Data.Entity.DbSet<WebApplication1.Models.LoginModel> LoginModels { get; set; }
    }
    public class Categories
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool status { get; set; }
        public virtual List<Product> Products { get; set; }
    }
    public class Products
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string Decription { get; set; }
        public float Price { get; set; }
        public int Quantity { get; set; }
        public string Image { get; set; }
        public int CategoryId { get; set; }

        public bool status { get; set; }
        public virtual Category category { get; set; }
        public virtual List<InvoiceDetail> invoiceDetail { get; set; }


    }
    public class Accounts
    {
        [DisplayName("Mã đăng nhập")]
        [Required]
        public int Id { get; set; }

        [DisplayName("Tên đăng nhập")]
        [Required]
        public string username { get; set; }

        [DisplayName("Mật khẩu")]
        [Required, MinLength(8), MaxLength(16)]
        public string password { get; set; }

        [DisplayName("Email")]
        [Required, EmailAddress]
        public string email { get; set; }

        [DisplayName("sdt")]
        public string sdt { get; set; }

        [DisplayName("Tên đầy đủ")]
        [Required]
        public string fullname { get; set; }

        [DisplayName("là admin")]

        public bool isAdmin { get; set; }

      

       

      

        public virtual List<Invoice> Invoices { get; set; }

    }
    public class Invoices
    {
        public int Id { get; set; }

        public string code { get; set; }
        public int AccountId { get; set; }
        public System.DateTime invoiceDay { get; set; }
        public string shippingAddress { get; set; }
        public string shippingPhone { get; set; }
        public int total { get; set; }

        public bool status { get; set; }
        public virtual Account Account { get; set; }
        public virtual List<InvoiceDetail> InvoiceDetails { get; set; }
    }

    public class InvoiceDetails
    {
        public int Id { get; set; }
        public int InvoiceDetail { get; set; }
        public int ProductId { get; set; }
        public int Quatity { get; set; }
        public int UnitPrice { get; set; }

        public virtual Invoice Invoice { get; set; }
        public virtual Product Product { get; set; }
    }
}
